name=BluetoothSerial
version=3.3.7.2
author=Evandro Copercini, Tobias Hahnen
maintainer=DIMATE GmbH <support@dimate.de>
sentence=Simple UART to Classical Bluetooth bridge for ESP32
paragraph=Patched version only supporting Bluetooth Classic and slave mode.
category=Communication
url=
architectures=esp32
